# -*- coding: utf-8 -*-
"""FruitClassification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xve0t8JPf1uTn7GyVtQc0leVTAaEjy2F
"""

from keras.models import load_model  # TensorFlow is required for Keras to work
from PIL import Image, ImageOps  # Install pillow instead of PIL
import numpy as np
import tf_keras as tk

# Disable scientific notation for clarity
np.set_printoptions(suppress=True)

# Load the model
model = tk.models.load_model("keras_model.h5", compile=False)

# Load the labels
class_names = open("labels.txt", "r").readlines()

# Create the array of the right shape to feed into the keras model
# The 'length' or number of images you can put into the array is
# determined by the first position in the shape tuple, in this case 1
data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)

# Replace this with the path to your image
image = Image.open("/content/Mango (58).jpeg").convert("RGB")

# resizing the image to be at least 224x224 and then cropping from the center
size = (224, 224)
image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)

# turn the image into a numpy array
image_array = np.asarray(image)

# Normalize the image
normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

# Load the image into the array
data[0] = normalized_image_array

# Predicts the model
prediction = model.predict(data)
index = np.argmax(prediction)
class_name = class_names[index]
confidence_score = prediction[0][index]

# Print prediction and confidence score
print("Class:", class_name[2:], end="")
print("Confidence Score:", confidence_score)

!pip install gradio tf-keras -q

import tf_keras as tk
from PIL import Image, ImageOps
import numpy as np
import gradio as gr

# تحميل النموذج
model = tk.models.load_model("keras_model.h5", compile=False)

# تحميل أسماء الفئات
class_names = open("labels.txt", "r").readlines()

def predict(image):

    # تجهيز الصورة
    size = (224, 224)
    image = image.convert("RGB")
    image = ImageOps.fit(image, size, Image.Resampling.LANCZOS)

    image_array = np.asarray(image)

    normalized_image_array = (image_array.astype(np.float32) / 127.5) - 1

    data = np.ndarray(shape=(1, 224, 224, 3), dtype=np.float32)
    data[0] = normalized_image_array

    # التنبؤ
    prediction = model.predict(data, verbose=0)

    index = np.argmax(prediction)

    class_name = class_names[index][2:].strip()
    confidence = float(prediction[0][index] * 100)

    return f"🍎 الفاكهة: {class_name}\n\n📊 نسبة الثقة: {confidence:.2f}%"

demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil", label="ارفع صورة الفاكهة"),
    outputs=gr.Textbox(label="النتيجة"),
    title="🍓 Fruit Classifier",
    description="ارفع صورة وسيقوم النموذج بتحديد نوع الفاكهة.",
)

demo.launch(share=True)